version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  redis01:
#    image: bitnami/redis:latest
    image: arm64v8/redis
    container_name: redis_01
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - ./redis_01/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  redis02:
#    image: bitnami/redis:latest
    image: arm64v8/redis
    container_name: redis_02
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6400:6400"
    volumes:
      - ./redis_02/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
#  rabbitmq:
#    image: bitnami/rabbitmq:latest
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"

volumes:
  elasticsearch-data:
    driver: local